_format_version: "3.0"
services:
  - name: identity-svc
    url: http://identity-svc:4001
    routes:
      - name: auth-routes
        paths:
          - /api
        strip_path: true

  - name: product-service
    url: http://product-svc:4002
    routes:
      - name: product-route
        paths:
          - /api/products
    plugins: # Chỉ đặt bảo mật cho những service cần thiết
      - name: jwt
      
  - name: order-service
    url: http://order-svc:4003
    routes:
      - name: order-route
        paths:
          - /api/orders
    plugins: # Chỉ đặt bảo mật cho những service cần thiết
      - name: jwt

  - name: report-service
    url: http://report-svc:4004
    routes:
    - name: report-route
      paths:
        - /api/reports
      strip_path: true

plugins:
  - name: prometheus # Tự động thu thập chỉ số cho tất cả service
  - name: rate-limiting
    config:
      minute: 60
      policy: local # Giới hạn chung 60 request/phút cho toàn bộ API
  - name: cors # Cho phép mọi Frontend truy cập vào các service
    config:
      origins: 
        - http://localhost:3000
      methods: ["GET", "POST", "PUT", "DELETE"]
      headers:
        - Accept
        - Accept-Control-Allow-Origin
        - Content-Type
        - Authorization
        - Cookie
        - X-Requested-With
      exposed_headers: ["Set-Cookie"]
      credentials: true