_format_version: "3.0"
services:
  - name: product-service
    url: http://product-svc:4000
    routes:
      - name: product-route
        paths:
          - /api/products
  - name: order-service
    url: http://order-svc:5000
    routes:
      - name: order-route
        paths:
          - /api/orders
plugins:
  - name: jwt # Bảo mật các route bằng Token Firebase